//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyVersionAttribute("0.10.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("0.10.2")]

// Generated by the MSBuild WriteCodeFragment class on 23/11/2014 9:25:43 PM.

